apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stage6-api.fullname" . }}
  labels:
    {{- include "stage6-api.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.APP_ENV | quote }}
  APP_MESSAGE: {{ .Values.config.APP_MESSAGE | quote }}
