apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stage6-api.fullname" . }}
  labels:
    {{- include "stage6-api.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "stage6-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "stage6-api.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
          envFrom:
            - configMapRef:
                name: {{ include "stage6-api.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
